### ISSUE TITLE
Compatibility with puma v6

### ISSUE THREAD

**Issue by marocchino** [testdouble/cypress-rails#135]
## Meta

puma: 6.0.0
cypress-rails: 0.5.4
ralis: 6.1.7

## Behavior

Checking the latest version of puma (v6) released yesterday
Running my test suite causing

```
Run bundle exec rails cypress:run
#<Thread:0x00007f30a04b3160 /home/runner/work/cache/bundle/ruby/3.1.0/gems/cypress-rails-0.5.4/lib/cypress-rails/server.rb:74 run> terminated with exception (report_on_exception is true):
/home/runner/work/cache/bundle/ruby/3.1.0/gems/cypress-rails-0.5.4/lib/cypress-rails/server/puma.rb:15:in `create': undefined method `stdio' for Puma::Events:Class (NoMethodError)

        events = ::Puma::Events.stdio
                               ^^^^^^
	from /home/runner/work/cache/bundle/ruby/3.1.0/gems/cypress-rails-0.5.4/lib/cypress-rails/server.rb:75:in `block in boot'
/home/runner/work/cache/bundle/ruby/3.1.0/gems/cypress-rails-0.5.4/lib/cypress-rails/server/puma.rb:15:in `create': undefined method `stdio' for Puma::Events:Class (NoMethodError)

        events = ::Puma::Events.stdio
                               ^^^^^^
	from /home/runner/work/cache/bundle/ruby/3.1.0/gems/cypress-rails-0.5.4/lib/cypress-rails/server.rb:75:in `block in boot'
```

**Comment by searls** [comment]
Thanks for submitting this. Running your PR against the existing tests now and will cut a release if it passes

**Comment by marocchino** [comment]
I checked new release with puma 6. 👍🏽
